"""
Login Response

Paper Mapping
-------------
Section V-C
Step 3

Authentication Server
        ↓
        User

The server returns an authentication proof (v)
computed using the established session key.
"""

from dataclasses import dataclass


@dataclass(slots=True)
class LoginResponse:
    """
    Authentication response generated by the
    Authentication Server.

    Paper
    -----
    v = H1(K || γi || T1 || rt)
    """

    # ======================================================
    # Authentication Proof
    # ======================================================

    verification: bytes